# Generated by Django 4.0.4 on 2022-07-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackbee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zbconvert',
            name='status_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zbgoodfind',
            name='guesses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zbgoodfind',
            name='key',
            field=models.CharField(max_length=129, null=True),
        ),
        migrations.AlterField(
            model_name='zbgoodfind',
            name='status_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zbreplay',
            name='results',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zbreplay',
            name='status_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
